ios support
libretro/flycast pull request #700
Opened 2019-10-19 01:23 UTC by jet082

Tested and working.

2019-10-21 10:13 UTC, flyinghead requested changes

2019-10-21 10:13 UTC, flyinghead commented on Makefile
> +		HOST_CPU_FLAGS = -DHOST_CPU=$(DYNAREC_NONE)
This is not the way `HOST_CPU` should be used. For iOS it's supposed to be HOST_CPU_ARM64. You can add an iOS target in build.h and set the various defines there (`FEAT_SHREC`, `FEAT_AREC`, `FEAT_DSPREC`, ...)

2019-10-21 10:13 UTC, flyinghead commented on core/hw/sh4/sh4_core_regs.cpp
> +#elif HOST_CPU == CPU_ARM64 || defined(IOS)
This shouldn't be needed if `HOST_CPU` is correct

2019-10-21 10:13 UTC, flyinghead commented on core/libretro/vmem_utils.cpp
> +		#ifndef IOS
I don't think it's OK if this call fails on iOS. Probably it shouldn't be called at all, or the result should be checked.
This is required to detect texture updates even when using the interpreter.

2019-10-21 10:13 UTC, flyinghead commented on core/libretro/vmem_utils.cpp
> +		#ifndef IOS
same comment as above

2019-10-21 10:13 UTC, flyinghead commented on core/libretro/vmem_utils.cpp
> +		#ifndef IOS
Same although this one is only used when using a dynarec iirc

2019-10-21 10:13 UTC, flyinghead commented on core/serialize.cpp
> +	#if FEAT_SHREC != DYNAREC_NONE
This makes the save state format differ when using a dynarec and when not using one. Here the `cycle_counter` doesn't need to be de/serialized anyway so just do:
```
    LIBRETRO_S(i); // cycle_counter
```

2019-10-21 10:13 UTC, flyinghead commented on core/serialize.cpp
> +	#if FEAT_SHREC != DYNAREC_NONE
Same problem as above. Simply do:
```
    LIBRETRO_US(dummy_int); // cycle_counter
```

2019-11-15 00:53 UTC, twinaphex commented
Hi @jet082, can you rebase this?

2020-08-16 04:12 UTC, closed without merging

2020-08-18 08:45 UTC, dankcushions commented
closed during hack-gate 2020. @twinaphex please re-open :)